name: Deploy backend (deploy.dyzoon.dev)
'on':
  push:
    branches:
      - main
  workflow_dispatch: null
jobs:
  docker:
    name: Publish - Github Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push to Container Registry
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          provenance: false
          platforms: linux/arm64/v8
          tags: ghcr.io/airqua/airqua-mqtt:latest
  deploy:
    name: Call redeployment webhook
    needs: [docker]
    runs-on: ubuntu-latest
    steps:
      - name: Execute webhook
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.DEPLOY_WEBHOOK_URL }}
          body: '{}'
